# Example jsonmon configuration. Public domain
# Docs: https://github.com/chillum/jsonmon/wiki/Configuration

# Checks once in a minute and does not notify by email:
- name:   Yandex
  web:    https://ya.ru
  match:  Найти
  tries:  3 # Optional attempts number.
# Checks once in 10 seconds:
- web:    http://192.168.6.1
  repeat: 10
  notify: me@localhost
# Pings once in 2 seconds:
- shell:  ping -t 1 192.168.6.1
  repeat: 2
  notify:
    - me@localhost
    - sales@server